[supervisord]
nodaemon=true

[program:xrdp]
command=/usr/sbin/xrdp -nodaemon
redirect_stderr=true
stdout_logfile=/var/log/xrdp.log

[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman --nodaemon
redirect_stderr=true
stdout_logfile=/var/log/xrdp-sesman.log
